// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_application_1/test/model/api/detail_project_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_application_1/model/api/detail_project_api.dart' as _i2;
import 'package:flutter_application_1/model/detail_project.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DetailProjectAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailProjectAPI extends _i1.Mock implements _i2.DetailProjectAPI {
  MockDetailProjectAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.DetailProject>> getDetailProject(int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetailProject, [id]),
              returnValue:
                  Future<List<_i4.DetailProject>>.value(<_i4.DetailProject>[]))
          as _i3.Future<List<_i4.DetailProject>>);
  @override
  _i3.Future<bool> addDetailProject(_i4.DetailProject? detailProject) =>
      (super.noSuchMethod(Invocation.method(#addDetailProject, [detailProject]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> deleteDetailProject(int? id) =>
      (super.noSuchMethod(Invocation.method(#deleteDetailProject, [id]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> updateDetailProject(int? id, bool? status) =>
      (super.noSuchMethod(Invocation.method(#updateDetailProject, [id, status]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
