// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_application_1/test/model/api/users_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_application_1/model/api/users_api.dart' as _i2;
import 'package:flutter_application_1/model/users_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserAPI extends _i1.Mock implements _i2.UserAPI {
  MockUserAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> regis(_i4.User? user) =>
      (super.noSuchMethod(Invocation.method(#regis, [user]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<Map<String, dynamic>> login(_i4.User? user) => (super.noSuchMethod(
          Invocation.method(#login, [user]),
          returnValue: Future<Map<String, dynamic>>.value(<String, dynamic>{}))
      as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<bool> resetPassword(int? id, String? password) =>
      (super.noSuchMethod(Invocation.method(#resetPassword, [id, password]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
